name: Run tests
run-name: ${{ github.workflow }} - running in ${{ github.repository }}, triggered by ${{ github.event_name }}
on: [ push ]
jobs:
  Run-ShellSpec-Tests:
    runs-on: ubuntu-22.04
    steps:
      - name: "Check out"
        uses: actions/checkout@v4
      - name: "Install ShellSpec"
        run: |
          cd test
          ./install_shellspec.sh
      - name: "Run ShellSpec tests"
        run: |
          cd test
          ./run_shellspec_tests.sh
